### ISSUE TITLE
[bug] Output option required but not used

### ISSUE THREAD

**Issue by johnmee** [fdavies93/seneca#1]
The `--output` is a mandatory input, but is ignored.

Expected:

When I run `python senca.py --input wise-transactions.csv` I expected it to write the output to stdout.

Observed:

```
usage: seneca.py [-h] --input INPUT --output OUTPUT [--map MAP]
seneca.py: error: the following arguments are required: --output/-o
```

Expected:

When I run `python seneca.py --input wise-transactions.csv --output foo.beancount` I expected the output to be deposited into the file foo.beancount.

Observed:

The output was written to stdout, but no file was created.

Recommendation:

Drop the `output` parameter.  As you said in the readme, if you want it to file then redirect the stdout.

**Comment by fdavies93** [comment]
Removed `--output` option and updated directly.
